zendeskgarden/css-components

- packages/arrows/CHANGELOG.md
- packages/arrows/README.md
- packages/avatars/README.md
- packages/bedrock/README.md
- packages/buttons/README.md
- packages/callouts/README.md
- packages/chrome/README.md
- packages/forms/README.md
- packages/menus/README.md
- packages/modals/README.md
- packages/pagination/README.md
- packages/tables/README.md
- packages/tabs/README.md
- packages/tags/README.md
- packages/tooltips/README.md
- packages/utilities/README.md
- packages/variables/README.md
All package README files are still pointing to outdated `@zendesk/garden-css-[package]` names.
> fix: document corrected `@zendeskgarden` package scope

- packages/.template/README.md
- packages/arrows/README.md
- packages/avatars/README.md
- packages/bedrock/README.md
- packages/buttons/README.md
- packages/callouts/README.md
- packages/chrome/README.md
- packages/forms/README.md
- packages/menus/README.md
- packages/modals/README.md
- packages/pagination/README.md
- packages/tables/README.md
- packages/tabs/README.md
- packages/tags/README.md
- packages/tooltips/README.md
- packages/utilities/README.md
- packages/variables/README.md
removes the `--save-dev` flag from the bed-rock install `README.md` file. 
> fix: remove save-dev from bedrock install instructions

- demo/arrows/index.html
- packages/arrows/src/_base.css
Added:
* `.c-arrow--rt`
* `.c-arrow--rb`
* `.c-arrow--lt`
* `.c-arrow--lb`
> feat(arrows): add new right/left positioning classes

- demo/buttons/index.html
- demo/forms/dropdown/index.html
- demo/tabs/index.html
Update to point to the new `react-components`.
> chore: fix demo page React links

- demo/tags/index.html
- packages/tags/src/_avatar.css
- packages/tags/src/_base.css
- packages/tags/src/_remove.css
- packages/tags/src/_size.css
* update avatar/remove offset margins to correspond with updated base-4 tag padding
* fix broken selector for remove styling on color tags
* link tags updated to receive `pointer` cursor
> fix(tags): correct base-4 element margins and remove styling for color tags

- demo/grid/index.css
- demo/grid/index.html
- demo/grid/index.js
- demo/index.html
- packages/grid/README.md
- packages/grid/package.json
- packages/grid/src/index.scss
- yarn.lock
This PR introduces the `@zendeskgarden/css-layout` package. This package is an opinionated wrapper around the [Bootstrap v4 Flexbox Grid](https://getbootstrap.com/docs/4.1/layout/grid/).
The customizations are:
* Gutter size of 20px
* `is-rtl` class to apply RTL styling (🎉 yay flexbox)
* `debug` class to apply blue styling on columns to more easily debug grid sizes 
Pre-published at: https://garden.zendesk.com/css-components/grid/
> feat(layout): introduce @zendeskgarden/css-layout package

- packages/grid/package.json
- packages/grid/src/index.scss
* The `styles` property in the package.json was invalid. This PR removes that entry.
* When consumed through `css-modules` the `is-debug` styling was invalid for all columns that had a number or breakpoint value. This adds a wildcard attribute to apply to ALL `col` classes within it. 
> fix(grid): apply debug styling to all columns

- packages/grid/src/index.scss
This Pr fixes 2 things relating to the `box-sizing` fix for css-grid.
* Turns out the `::before` and `::after` syntax wasn't valid SCSS. This is now fixed.
* Due to use removing the global, HTML `box-sizing`, we have to apply it directly to `.container` and `.container-fluid` rather than inheriting it.
> fix(grid): apply border-box sizing to containers

- demo/modals/index.html
- packages/modals/src/_close.css
- packages/modals/src/_footer.css
- yarn.lock
Add `20px` spacing for buttons within a modal dialog's footer.
Demo is published for review: https://garden.zendesk.com/css-components/modals/
> feat(modals): incorporate spacing for footer buttons

- demo/utilities/spacing/index.html
- packages/callouts/src/_base.css
- packages/forms/src/_checkbox/_base.css
- packages/menus/src/_item.css
- packages/modals/src/_close.css
- packages/tags/src/_remove.css
- packages/tags/src/_size.css
- packages/utilities/src/spacing.css
- packages/variables/src/_spacing.js
| BEFORE | AFTER |
| -------- | ------- |
| `--zd-spacing-xxs: 2px` | `--zd-spacing--xxs: 4px` |
| `--zd-spacing--xs: 5px` | `--zd-spacing--xs: 8px` |
| `--zd-spacing--sm: 10px` | `--zd-spacing--sm: 12px` |
| `--zd-spacing: 20px` | `--zd-spacing: 20px` |
| `--zd-spacing--lg: 30px` | `--zd-spacing--lg: 32px` |
| `--zd-spacing--xl: 40px` | `--zd-spacing--xl: 40px` |
| NA | `--zd-spacing--xxl: 48px` |
All `.u-m[*]` and `.u-p[*]` spacing utilities are updated accordingly with additions for XXL.
* Replaced outdated component variable usage with absolute pixel units.
* Pre-deployed and spot-checked garden.zendesk.com website with no observable differences.
* [] :white_check_mark: all component states are represented
primary accent …
> feat(variables, utilities): update with base4 spacing

- demo/chrome/page.html
- packages/chrome/src/_nav.css
- yarn.lock
Prevent `.c-chrome__nav__item` from shrinking when `.c-chrome__nav` height is less than the height of it's child contents.
closes https://github.com/zendeskgarden/css-components/issues/77
> fix(chrome): prevent shrinking nav items

- packages/tables/src/_overflow.css
When the `.c-table__row__cell__overflow` class is applied the element does not have a specified width. This can cause invalid positioning when used with our `react-menus` package.
This PR specifies the width to match 100% of it's container, similar to it's height.
> fix(tables): specify width of row overflow button

- packages/chrome/src/_subnav.css
Sub nav items currently do not reset the cursor to `default` when they're active, this changes matches the top level nav behaviour.
> fix(chrome): Reset cursor to default on active sub nav item

- packages/modals/src/_footer.css
Change modal footer to use flex-box.
> LTR
> RTL
Closes #86 
☝️ tested in Chrome, Firefox, and Safari
> fix(modals): increase flexibility of footer alignment

- demo/chrome/index.html
- demo/chrome/page.html
- packages/chrome/src/_nav.css
- packages/chrome/src/_subnav.css
- yarn.lock
Add `.c-chrome__nav__item__text--wrap` and `.c-chrome__subnav__item__text--wrap` to support styling for longer navigation text that needs to wrap.
closes #82 
> feat(chrome): update nav elements with option to wrap text

- demo/chrome/index.html
- packages/chrome/src/_nav.css
- packages/chrome/src/_subnav.css
Currently if `c-chrome__subnav__item` elements are rendered using `<button>` elements, wrapped text will incorrectly center.
> fix(chrome): add subnav styling resets

- demo/chrome/index.html
- demo/chrome/page.html
- demo/chrome/tinycolor.js
- lerna.json
- package.json
- packages/chrome/package.json
- packages/chrome/src/_nav.css
- yarn.lock
Adds a `.c-chrome__nav__item--brandmark` class for styling a brandmark logo in the side nav.
> feat(chrome): add brandmark element styling

- .travis.yml
The symlink => regular file conversion was required by the Travis "pages" provider, which is no longer used.
> chore: prevent uncommitted changes from breaking `lerna publish`

- demo/menus/index.html
- packages/menus/src/_item.css
Garden designs have been updated and call for menu items to appear nested below associated header elements.
* Added: `.c-menu__item--header--icon` needed to prepare the header element for receiving a child `.c-menu__item--header__icon` element (this is a breaking addition now required for icon-styled header elements).
* Updated: increased horizontal padding for `.c-menu__item` from 24px to 32px (small sized menu items increase from 20px to 24px).
* Updated: `.c-menu__item--header__icon` position adjusted accordingly.
> fix(menus): update item indentation

- demo/tables/index.html
- packages/tables/src/_overflow.css
A 100% row height click area for the overflow trigger is unintuitive and makes menu component positioning unmanageable. With a fixed height of `2em`, a separate React menu component can be reliably positioned at `calc(2em + 1px)` from the top of the overflow element – regardless of table row size. 
Demo is prepublished for review at https://garden.zendesk.com/css-components/tables/
> fix(tables): adjust `.c-table__row__cell__overflow` trigger size

- packages/menus/src/_item.css
- packages/menus/src/_state.css
- packages/menus/src/custom.css
Focus behavior for menu items should be both stylistically and behaviorally interchangeable with hover. i.e. remove focus on hover; remove hover on focus. Only one menu item should ever receive focus or hover at a time.
Demo prepublished for review https://garden.zendesk.com/css-components/menus/
> fix(menus): remove `box-shadow` on `.c-menu__item.is-focused`

- packages/chrome/README.md
`.c-chrome__body__content` should be a child of `c-chrome__body` and `main` tags are not self-closing.
> docs(chrome): corrects hierarchy and syntax

- demo/modals/index.html
- packages/buttons/src/_base.css
- packages/modals/src/_footer.css
* Update `.c-btn` to use `text-overflow: ellipsis`.
* Update `.c-dialog__footer__item` display flex with `min-width: 0`.
Demo published for review https://garden.zendesk.com/css-components/modals/ (use Playground to test).
> fix(buttons|modals): prevent modal footer item overflow

- packages/modals/src/_body.css
Headers and footers should remain visible even if body content overflows the modal container.
Published for review https://garden.zendesk.com/css-components/modals/
> fix(modals): header/footer remain fixed as body content scrolls

- demo/modals/index.html
- packages/modals/src/_body.css
- packages/modals/src/_footer.css
Modal layout (default size; long body content) broke with #132. This PR adjusts padding to prevent that.
> fix(modals): prevent body overflow on to footer

- packages/forms/src/_text/_media.css
... regardless of inclusion of optional `.c-txt__input--media__figure` start/end components.
> fix(forms): apply consistent padding to .c-txt__input--media

- demo/forms/text/index.html
- packages/forms/src/_text/_media.css
> fix(forms): correct margins for `.c-txt__input--media` RTL layout

- demo/utilities/color/index.html
- demo/utilities/index.html
- package.json
- packages/utilities/src/color.css
- packages/variables/src/_color.js
- yarn.lock
...along with product color utility classes:
* `chat-orange`
* `connect-red`
* `explore-blue`
* `guide-pink`
* `message-green`
* `support-green`
* `talk-yellow`
Demo pre-published for review: https://garden.zendesk.com/css-components/utilities/color/
> feat(variables|utilities): add `sell-gold` color

- demo/avatars/index.html
- packages/avatars/src/_base.css
- packages/avatars/src/_size.css
Default size has changed to new 40px size and older sizes have had their names changed
Introduce a new default 40px size avatar and change other sizes to base-4 system.
| Size | px |
|-----------|----|
| xs | 24px |
| sm | 32px |
| default | 40px |
| lg | 48px |
| Size | px |
|------|----|
| small | 26px |
| default | 34px |
| large | 52px |
Pre-published: https://garden.zendesk.com/css-components/avatars/
> feat(avatars): Add new 40px size and rename other sizes

- packages/breadcrumbs/src/_item.css
fix needed for https://github.com/zendeskgarden/react-components/pull/215
Demo pre-published for review at https://garden.zendesk.com/css-components/breadcrumbs/.
> fix(breadcrumbs): chevron separator positioning

- packages/chrome/src/_nav.css
...from 50px to 52px to honor base-4 sizing.
Demo pre-published for review https://garden.zendesk.com/css-components/chrome/
> fix(chrome): bump `c-chrome__nav__item` height

- packages/forms/src/_checkbox/_state.css
- packages/forms/src/custom.css
Extra spaces added to compiled CSS are throwing off `indeterminate` checkbox styling, along with the more subtle "active" state.
See https://github.com/postcss/postcss-custom-selectors/issues/40 for details.
> fix(forms): checkbox workaround for invalid `postcss-custom-selectors` transform spacing

- .prettierrc
- demo/arrows/index.html
- demo/buttons/index.html
- demo/chrome/index.html
- demo/chrome/index.js
- demo/chrome/page.html
- demo/forms/checkbox/index.html
- demo/forms/dropdown/index.html
- demo/forms/dropdown/index.js
- demo/forms/range/index.html
- demo/forms/text/index.html
- demo/index.html
- demo/menus/index.html
- demo/menus/index.js
- demo/pagination/index.html
- demo/tables/index.html
- demo/tabs/index.html
- demo/tags/index.html
- packages/menus/src/_keyframes.css
This PR is the first step to allow support for top and left animations to work correctly with popper.js in our select & menu components.
The real change is just using top, left, right & bottom instead of margins. 
Popper positions the element using a transform so top, left, right & bottom are relative to that gpu layer and not to the document.
Here's this running locally for react-menus
I added a .prettierrc file that matches react-components.
The demo page needed some changes to support working with the new usage of position properties over using margins to emulate what popper would do.
> fix(menus): Support top & left animations

- packages/breadcrumbs/src/_state.css
> fix(breadcrumbs): inherit current link color on hover/focus

- demo/arrows/index.html
- demo/buttons/index.html
- demo/buttons/index.js
- demo/chrome/index.html
- demo/chrome/page.html
- demo/forms/checkbox/index.html
- demo/forms/dropdown/index.html
- demo/forms/range/index.html
- demo/forms/text/index.html
- demo/forms/text/index.js
- demo/menus/index.html
- demo/pagination/index.html
- demo/tables/index.html
- demo/tabs/index.html
- demo/tags/index.html
- packages/buttons/src/_state.css
- packages/buttons/src/custom.css
- packages/forms/src/_text/_state.css
- packages/forms/src/_text/_validation.css
- packages/forms/src/_variables.css
- packages/forms/src/custom.css
Provide a way to inset box-shadow styling for focused buttons and text fields.
Demo pages are pre-published for review. See "Inset Focus" toggle under the settings menu for the following pages:
https://garden.zendesk.com/css-components/buttons/
https://garden.zendesk.com/css-components/forms/dropdown/
https://garden.zendesk.com/css-components/forms/text/
> feat(buttons|forms): add `--focus-inset` styling variant

- demo/utilities/color/index.html
- packages/utilities/src/color.css
- packages/variables/src/_color.js
New 400/600 colors:
* fuschia
* pink
* crimson
* orange
* lemon
* lime
* mint
* teal
* azure
* royal
* purple
Demo pre-published for review: https://garden.zendesk.com/css-components/utilities/color/
> feat(variables|utilities): add secondary colors

- demo/chrome/index.html
- demo/chrome/page.html
- packages/chrome/src/_base.css
- packages/chrome/src/_footer.css
- packages/chrome/src/index.css
Provides a new bottom bar for Save/Cancel type actions.
Demo is pre-published for review: https://garden.zendesk.com/css-components/chrome/
> feat(chrome): add new `.c-chrome__body__footer` bottom action bar.

- demo/forms/dropdown/index.html
- packages/forms/src/_text/_bare.css
- packages/forms/src/_text/_size.css
Provide styling to manage the size of a dropdown chevron when the field is styled using the `.c-txt__input--bare` modifier.
Demo is pre-published for review: https://garden.zendesk.com/css-components/forms/dropdown/. Use menu settings to alter component styling.
> fix(forms): bare-styled select chevron sizing

- demo/forms/text/index.js
- packages/forms/src/_text/_media.css
- packages/forms/src/_text/_size.css
Also apply `cursor: text` to `.c-txt__input--media` elements.
Partially addresses https://github.com/zendeskgarden/react-components/issues/265
> fix(forms): padding/margin for small `.c-txt__input--media` element

- demo/callouts/index.html
- packages/callouts/src/_color.css
Adds a `.c-callout--info` class that can be used for information wells and notification styling.
Demo pre-published for review: https://garden.zendesk.com/css-components/callouts/
> feat(callouts): add info styling

- demo/utilities/color/index.html
- packages/utilities/src/color.css
- packages/variables/scripts/build.js
- packages/variables/src/_color.js
Adds `M400/600` colors to the secondary palette.
Demo pre-published for review: https://garden.zendesk.com/css-components/utilities/color/
> feat(variables|utilities): add muted secondary colors

- packages/menus/src/_item.css
Several `react-components` wrap menu items in a container for enhanced overflow support. Unitless line heights produce unexpected wrapper scrollbars in Chrome browsers. Providing definite pixel heights fixes Chrome's ability to calculate the correct height for the container <div>.
addresses https://github.com/zendeskgarden/react-components/issues/279
> fix(menus): express item line-height via explicit pixels

- demo/utilities/color/index.html
Update to display the correct variable value: `#5d7df5`.
Demo has been pre-published for review: https://garden.zendesk.com/css-components/utilities/color/
> chore: fix demo hex value for `royal-400`

- demo/tags/index.html
- packages/tags/src/_color.css
- packages/tags/src/_remove.css
Adds:
* `.c-tag--azure`
* `.c-tag--crimson`
* `.c-tag--fuschia`
* `.c-tag--lemon`
* `.c-tag--lime`
* `.c-tag--mint`
* `.c-tag--orange`
* `.c-tag--pink`
* `.c-tag--purple`
* `.c-tag--royal`
* `.c-tag--teal`
Demo pre-published for review: https://garden.zendesk.com/css-components/tags/
> feat(tags): add secondary color styling modifiers

- demo/utilities/typography/index.html
- packages/utilities/src/font-size.css
- packages/variables/src/_font-size.js
Adds `sm`, `md`, and `lg` font sizing for the monospace font family.
The demo has been pre-published for review: https://garden.zendesk.com/css-components/utilities/typography/
A couple of items to note:
* We're testing more class combinations than Garden cares to utilize in product
* The existing `code` treatment is limited to the demo site but was updated to be very nearly accurate with updated designs
Both of these items will be 100% solved under `react-components`.
> feat(variables|utilities): add font sizes for monospace typography

- packages/chrome/src/_header.css
Addresses issue discussed under https://github.com/zendeskgarden/css-components/pull/186#pullrequestreview-229676833
> fix(chrome): prevent half pixel header item padding

- packages/chrome/src/_header.css
Got it wrong on https://github.com/zendeskgarden/css-components/pull/196 🤦‍♂ 
> fix(chrome): correct header item padding

- packages/forms/src/_range/_slider.css
Set to `default` (vs. `pointer`).
> fix(forms): disabled multi-range slider cursor

- demo/avatars/index.html
- demo/avatars/index.js
- packages/avatars/src/_badge.css
BREAKING CHANGE: removes `.c-avatar__badge` element in favor of expressing badge information via `data-badge` attribute. This change provides improved animation between statuses by not encouraging a re-render in React.
- Accessibility is precisely the same as before with `aria-live="polite"` added to the `.c-avatar` figure element.
- While this introduces a breaking change on the CSS side, the associated React component will be a patch version update as the contained badge element is an implementation detail.
> fix(avatars): use `::after` psuedo for status badge information

- demo/avatars/index.html
- packages/avatars/src/_base.css
- packages/avatars/src/_size.css
Use base-4 SVG sizing:
- xs = 12px
- sm = 12px
- md = 16px
- lg = 24px
Demo pre-published for review at: https://garden.zendesk.com/css-components/avatars/
> fix(avatars): adjust SVG sizing

- demo/utilities/list-style/index.html
- packages/utilities/src/list-style.css
Matches the `<ol> > <li>`/`<ul> > <li>` styling provided by `react-components`.
See https://github.com/zendeskgarden/react-components/pull/388.
Demo pre-published for review: https://garden.zendesk.com/css-components/utilities/list-style/
> feat(utilities): update `.u-list-style-*` styling

- demo/menus/index.html
- packages/menus/src/_base.css
- packages/menus/src/_item.css
Add `margin` to first and last menuitem instead of adding top/bottom padding to the menu container.
Demo pre-published for review: https://garden.zendesk.com/css-components/menus/ (see `max-height` example under "Sizing" section).
> fix(menus): prevent menu padding from clipping scrolled items

- demo/chrome/index.html
- packages/chrome/src/_base.css
- packages/chrome/src/_header.css
Addresses https://github.com/zendeskgarden/react-components/issues/423. After this modification, the issue screenshot looks like this:
Please note that the header item structure is expected to be something like the following:
```html
<div class="c-chrome__body__header__item c-chrome__body__header__item--max-x">
<span class="u-truncate">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>
</div>
```
...where the text content of the long header item is surrounded by a `<span>` that truncates with an ellipsis. Garden does not prevent overflow on Chrome header items because, in many cases, those items are meant to be menu triggers and `overflow: hidden` prevents a menu from being displayed. …
> fix(chrome): prevent body overflow due to wide header item

- packages/avatars/src/_badge.css
This fix is meant to prevent `box-sizing: border-box;` overrides that we are seeing when this component is used with `css-bedrock` in conjunction with other component CSS cascades.
> fix(avatars): force `content-box` sizing for the badge

- demo/utilities/color/index.html
- package.json
- packages/utilities/src/color.css
- packages/variables/src/_color.js
- yarn.lock
Demo pre-published for review: https://garden.zendesk.com/css-components/utilities/color/
> feat: add `gather-pink` variable and color utilities

- packages/forms/src/_text/_select.css
Fix for zendeskgarden/react-components#500
> fix(forms): apply default cursor to disabled select chevron

- packages/avatars/src/_base.css
Add object-fit cover to prevent broken image ratios
When using the `Avatar` component the image ratios should be kept. Adding `object-fit:cover` to the `img` would ensure that ratios are kept and it wouldn't affect the current behavior.
#248 
> fix(avatars): add object-fit cover to prevent broken image ratios

- packages/breadcrumbs/src/_item.css
Brought the chevron sizing down from `16px -> 12px`
Demo pre-published for review: https://garden.zendesk.com/css-components/breadcrumbs/
> fix(breadcrumbs): update breadcrumb icon size

- packages/bedrock/src/_base.css
The addition of `text-rendering: optimizeLegibility` can seriously impact load times for certain pages, especially when non-english character sets are involved.
Fixes #245.
> fix(bedrock): remove text-rendering property

- README.md
- demo/arrows/index.html
- demo/breadcrumbs/index.html
- demo/chrome/index.html
- demo/grid/index.html
- demo/index.html
- demo/menus/index.html
- demo/modals/index.html
- demo/pagination/index.html
- demo/scrollbars/index.html
- demo/tables/index.html
- demo/tabs/index.html
- demo/tooltips/index.html
The following CSS components have been deprecated in favor of fully-functional solutions provided by @zendeskgarden/react-components:
- Arrows
- Breadcrumbs
- Chrome
- Grid
- Menus
- Modals
- Pagination
- Scrollbars (no Garden alternative)
- Tables
- Tabs
- Tooltips
Although there will be no ongoing maintenance, these components will remain here indefinitely (several continue to be used to support website scaffold styling). However, each component will be marked with a message using `npm-deprecate` similar to https://www.npmjs.com/package/@zendeskgarden/react-autocomplete.
Demo pre-published to https://garden.zendesk.com/css-components/ for review.
> chore: deprecate non-native components

- demo/index.html
Put the `breadcrumbs` link back so that folks can navigate to the deprecated component – inadvertently removed in #274.
> chore: restore deprecated "breadcrumbs" demo link

- demo/bedrock/index.html
- packages/bedrock/src/_base.css
Bedrock is updated with the following:
- `<b>` = semibold (stylistic); currently **bold**
- `<em>` = normal/inherit (semantic); currently _italic_
- `<strong>` = regular/inherit (semantic); currently **bold**
Note
- `<i>` remains stylistic with _italic_
These changes will result in [`@zendeskgarden/css-bedrock`](https://www.npmjs.com/package/@zendeskgarden/css-bedrock) being upgraded to v8.0.0.
Demo pre-published for review with added tag treatments and playground: https://garden.zendesk.com/css-components/bedrock/
See UA defaults by turning off bedrock: https://garden.zendesk.com/css-components/bedrock/?bedrock=false
> feat(bedrock)!: apply opinionated semantic vs stylistic text markup defaults

- demo/arrows/index.html
- demo/breadcrumbs/index.html
- demo/chrome/index.html
- demo/grid/index.html
- demo/menus/index.html
- demo/modals/index.html
- demo/pagination/index.html
- demo/tables/index.html
- demo/tabs/index.html
- demo/tags/index.html
- demo/tooltips/index.html
With the new docs site there are several dead links throughout the CSS docs. I have updated the ones that have been fully migrated to their correct `garden.zendesk.com` links. For the other I've moved them to the `zendeskgarden.github.io` domain.
> fix(docs): update invalid links

- demo/index.html
- demo/utilities/index.html
This PR updates the documentation to reflect that `css-utilities` is now deprecated in favor of our [TailwindCSS plugin](https://github.com/zendeskgarden/tailwindcss).
> chore(docs): deprecate css-utilities

- demo/utilities/color/index.html
- package.json
- yarn.lock
This PR:
- Utilizes current `react-components` theming variables with updated brand colors
- Removes manually added (and out-of-date) hex values from the deprecated `css-utilities` demo page
> chore: update product colors

- .github/PULL_REQUEST_TEMPLATE.md
- packages/bedrock/README.md
- packages/bedrock/package.json
- packages/bedrock/src/index.css
Move from `Normalize.css` to `modern-normalize' – a smaller, tested, and more consistent option. While there are no observable differences, this needs to be marked as a BREAKING CHANGE as there may be underlying properties/overrides that certain code depends on or is not expecting.
> chore(bedrock)!: update normalize

- .github/renovate.json
Follow suit with the monorepo updates applied under https://github.com/zendeskgarden/react-components/pull/1202.
**Context:** this should substantially decrease the amount of Renovate noise currently being generated and get us back to a place (as intended by the original config) where a majority of minor/patch updates are consolidated under a single "shared dependencies" PR.
> chore(renovate): refactor config

- .circleci/config.yml
This PR adds `CACHE_VERSION` as a mechanism to cache busting.
> chore: add cache version key for circle ci cache busting

- .postcssrc.js
- packages/bedrock/src/_base.css
Updating `css-bedrock` with new focus treatment for `<a>` tags.
- Modifies the postcss configuration to use native `:focus-visible`
- Updates bedrock CSS to include focus styles for anchor with a `2px` `outline` (instead of `box-shadow`)
- Transition and color weights have parity with `react-components`
> feat(bedrock): add anchor focus styles
